// <auto-generated />
using System.Collections.Generic;

namespace EyuBot.Core.Configuration
{
    /// <summary>
    /// Main application configuration
    /// </summary>
    public class AppConfig
    {
        /// <summary>
        /// Gets or sets the agent configuration
        /// </summary>
        public AgentConfig Agent { get; set; } = new AgentConfig();

        /// <summary>
        /// Gets or sets the LLM provider configuration
        /// </summary>
        public LlmProviderConfig LlmProvider { get; set; } = new LlmProviderConfig();

        /// <summary>
        /// Gets or sets the MCP configuration
        /// </summary>
        public McpConfig Mcp { get; set; } = new McpConfig();

        /// <summary>
        /// Gets or sets the IM platform configurations
        /// </summary>
        public Dictionary<string, ImPlatformConfig> ImPlatforms { get; set; } = new Dictionary<string, ImPlatformConfig>();

        /// <summary>
        /// Gets or sets the skill configurations
        /// </summary>
        public Dictionary<string, SkillConfig> Skills { get; set; } = new Dictionary<string, SkillConfig>();
    }

    /// <summary>
    /// Agent configuration
    /// </summary>
    public class AgentConfig
    {
        /// <summary>
        /// Gets or sets the agent ID
        /// </summary>
        public string Id { get; set; } = "default-agent";

        /// <summary>
        /// Gets or sets the agent name
        /// </summary>
        public string Name { get; set; } = "EyuBot";

        /// <summary>
        /// Gets or sets the agent description
        /// </summary>
        public string Description { get; set; } = "An AI Agent powered by EyuBot framework";
    }

    /// <summary>
    /// LLM Provider configuration
    /// </summary>
    public class LlmProviderConfig
    {
        /// <summary>
        /// Gets or sets the provider name (e.g., OpenAI, Anthropic)
        /// </summary>
        public string ProviderName { get; set; } = "OpenAI";

        /// <summary>
        /// Gets or sets the API endpoint
        /// </summary>
        public string ApiEndpoint { get; set; } = "https://api.openai.com/v1/chat/completions";

        /// <summary>
        /// Gets or sets the API key
        /// </summary>
        public string ApiKey { get; set; } = "";

        /// <summary>
        /// Gets or sets the model name
        /// </summary>
        public string Model { get; set; } = "gpt-4";
    }

    /// <summary>
    /// MCP configuration
    /// </summary>
    public class McpConfig
    {
        /// <summary>
        /// Gets or sets whether MCP is enabled
        /// </summary>
        public bool Enabled { get; set; } = false;

        /// <summary>
        /// Gets or sets the MCP server URL
        /// </summary>
        public string ServerUrl { get; set; } = "http://localhost:5000";

        /// <summary>
        /// Gets or sets the MCP server token
        /// </summary>
        public string Token { get; set; } = "";
    }

    /// <summary>
    /// IM Platform configuration
    /// </summary>
    public class ImPlatformConfig
    {
        /// <summary>
        /// Gets or sets the platform name
        /// </summary>
        public string Name { get; set; } = "";

        /// <summary>
        /// Gets or sets the API key
        /// </summary>
        public string ApiKey { get; set; } = "";

        /// <summary>
        /// Gets or sets the bot token
        /// </summary>
        public string BotToken { get; set; } = "";

        /// <summary>
        /// Gets or sets the webhook URL
        /// </summary>
        public string WebhookUrl { get; set; } = "";

        /// <summary>
        /// Gets or sets whether the platform is enabled
        /// </summary>
        public bool Enabled { get; set; } = true;
    }

    /// <summary>
    /// Skill configuration
    /// </summary>
    public class SkillConfig
    {
        /// <summary>
        /// Gets or sets the skill name
        /// </summary>
        public string Name { get; set; } = "";

        /// <summary>
        /// Gets or sets the skill description
        /// </summary>
        public string Description { get; set; } = "";

        /// <summary>
        /// Gets or sets whether the skill is enabled
        /// </summary>
        public bool Enabled { get; set; } = true;

        /// <summary>
        /// Gets or sets the skill parameters
        /// </summary>
        public Dictionary<string, object> Parameters { get; set; } = new Dictionary<string, object>();
    }
}