// <auto-generated />
using System;
using System.Threading.Tasks;

namespace EyuBot.Core
{
    /// <summary>
    /// Base implementation of the IAgent interface
    /// </summary>
    public abstract class BaseAgent : IAgent
    {
        /// <summary>
        /// Gets the unique identifier of the agent
        /// </summary>
        public virtual string Id { get; protected set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// Gets the name of the agent
        /// </summary>
        public virtual string Name { get; protected set; } = "BaseAgent";

        /// <summary>
        /// Processes a message and returns a response
        /// </summary>
        /// <param name="message">The input message to process</param>
        /// <returns>The agent's response</returns>
        public abstract Task<string> ProcessMessageAsync(string message);

        /// <summary>
        /// Initializes the agent
        /// </summary>
        /// <returns>Awaitable task</returns>
        public virtual async Task InitializeAsync()
        {
            // Base initialization logic
            await Task.CompletedTask;
        }

        /// <summary>
        /// Disposes the agent resources
        /// </summary>
        /// <returns>Awaitable task</returns>
        public virtual async Task DisposeAsync()
        {
            // Base disposal logic
            await Task.CompletedTask;
        }
    }
}