// <auto-generated />
using System.Threading.Tasks;

namespace EyuBot.Core
{
    /// <summary>
    /// Defines the core interface for an AI Agent
    /// </summary>
    public interface IAgent
    {
        /// <summary>
        /// Gets the unique identifier of the agent
        /// </summary>
        string Id { get; }

        /// <summary>
        /// Gets the name of the agent
        /// </summary>
        string Name { get; }

        /// <summary>
        /// Processes a message and returns a response
        /// </summary>
        /// <param name="message">The input message to process</param>
        /// <returns>The agent's response</returns>
        Task<string> ProcessMessageAsync(string message);

        /// <summary>
        /// Initializes the agent
        /// </summary>
        /// <returns>Awaitable task</returns>
        Task InitializeAsync();

        /// <summary>
        /// Disposes the agent resources
        /// </summary>
        /// <returns>Awaitable task</returns>
        Task DisposeAsync();
    }
}